### ISSUE TITLE
K2P_3.4.3.9-099.trx自带的穿透服务阿里DDNS一直更新失败

### ISSUE THREAD

**Issue by yydls123** [chongshengB/rt-n56u#183]
Apr 19 12:20:45 【AliDDNS动态域名】: 开始更新 nas.xinxing.com 域名 IP 指向
Apr 19 12:20:45 【AliDDNS动态域名】: 目前 IP: 39.56.55.145
Apr 19 12:20:45 【AliDDNS动态域名】: 上次 IP: 192.168.2.200
Apr 19 12:20:50 【AliDDNS动态域名】: 添加的记录  
Apr 19 12:20:50 【AliDDNS动态域名】: 更新失败
Apr 19 12:20:50 【AliDDNS动态域名】: 更新动态DNS记录失败！请检查您的网络。

请C大看看能不能修复

**Comment by chongshengB** [comment]
哪个版本？

**Comment by yydls123** [comment]
3.4.3.9-099_20200417

最新版


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"chongshengB"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月19日(星期天) 中午12:41
收件人:&nbsp;"chongshengB/rt-n56u"<rt-n56u@noreply.github.com&gt;;
抄送:&nbsp;"65938872"<jerry86@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [chongshengB/rt-n56u] K2P_3.4.3.9-099.trx自带的穿透服务阿里DDNS一直更新失败 (#183)





 
哪个版本？

**Comment by yydls123** [comment]
还有能不能多集成几个穿透插件，最好有frp

**Comment by chongshengB** [comment]
你可以试试今天的，修复了，frp有不过要自己编译

**Comment by yydls123** [comment]
谢谢C大，我不会编译，希望以后有时间加上个FRP吧



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "chongshengB"<notifications@github.com&gt;; 
发送时间: 2020年4月19日(星期天) 中午12:52
收件人: "chongshengB/rt-n56u"<rt-n56u@noreply.github.com&gt;; 
抄送: "65938872"<jerry86@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [chongshengB/rt-n56u] K2P_3.4.3.9-099.trx自带的穿透服务阿里DDNS一直更新失败 (#183)





 
你可以试试今天的，修复了，frp有不过要自己编译
 
&mdash;

**Comment by butinhi** [comment]
> 你可以试试今天的，修复了，frp有不过要自己编译

这是什么错误？
Apr 19 11:46:23 dnsmasq-dhcp[849]: not giving name localhost.lan to the DHCP lease of 192.168.10.74 because the name exists in /etc/hosts with address 127.0.0.1
Apr 19 11:46:23 dnsmasq-dhcp[849]: not giving name localhost to the DHCP lease of 192.168.10.74 because the name exists in /etc/hosts with address 127.0.0.1
Apr 19 11:49:29 dnsmasq-dhcp[849]: not giving name localhost.lan to the DHCP lease of 192.168.10.74 because the name exists in /etc/hosts with address 127.0.0.1
Apr 19 11:49:29 dnsmasq-dhcp[849]: not giving name localhost to the DHCP lease of 192.168.10.74 because the name exists in /etc/hosts with address 127.0.0.1
Apr 19 11:53:30 dnsmasq-dhcp[849]: not giving name localhost.lan to the DHCP lease of 192.168.10.74 because the name exists in /etc/hosts with address 127.0.0.1
Apr 19 11:53:30 dnsmasq-dhcp[849]: not giving name localhost to the DHCP lease of 192.168.10.74 because the name exists in /etc/hosts with address 127.0.0.1
Apr 19 11:56:41 dnsmasq-dhcp[849]: not giving name localhost.lan to the DHCP lease of 192.168.10.74 because the name exists in /etc/hosts with address 127.0.0.1
Apr 19 11:56:41 dnsmasq-dhcp[849]: not giving name localhost to the DHCP lease of 192.168.10.74 because the name exists in /etc/hosts with address 127.0.0.1

**Comment by yydls123** [comment]
刚刷好，可以用了，下面的错误我也不知道，我的没有




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"butinhi"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月19日(星期天) 中午1:12
收件人:&nbsp;"chongshengB/rt-n56u"<rt-n56u@noreply.github.com&gt;;
抄送:&nbsp;"65938872"<jerry86@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [chongshengB/rt-n56u] K2P_3.4.3.9-099.trx自带的穿透服务阿里DDNS一直更新失败 (#183)





  
你可以试试今天的，修复了，frp有不过要自己编译
  
这是什么错误？
 Apr 19 11:46:23 dnsmasq-dhcp[849]: not giving name localhost.lan to the DHCP lease of 192.168.10.74 because the name exists in /etc/hosts with address 127.0.0.1
 Apr 19 11:46:23 dnsmasq-dhcp[849]: not giving name localhost to the DHCP lease of 192.168.10.74 because the name exists in /etc/hosts with address 127.0.0.1
 Apr 19 11:49:29 dnsmasq-dhcp[849]: not giving name localhost.lan to the DHCP lease of 192.168.10.74 because the name exists in /etc/hosts with address 127.0.0.1
 Apr 19 11:49:29 dnsmasq-dhcp[849]: not giving name localhost to the DHCP lease of 192.168.10.74 because the name exists in /etc/hosts with address 127.0.0.1
 Apr 19 11:53:30 dnsmasq-dhcp[849]: not giving name localhost.lan to the DHCP lease of 192.168.10.74 because the name exists in /etc/hosts with address 127.0.0.1
 Apr 19 11:53:30 dnsmasq-dhcp[849]: not giving name localhost to the DHCP lease of 192.168.10.74 because the name exists in /etc/hosts with address 127.0.0.1
 Apr 19 11:56:41 dnsmasq-dhcp[849]: not giving name localhost.lan to the DHCP lease of 192.168.10.74 because the name exists in /etc/hosts with address 127.0.0.1
 Apr 19 11:56:41 dnsmasq-dhcp[849]: not giving name localhost to the DHCP lease of 192.168.10.74 because the name exists in /etc/hosts with address 127.0.0.1
